// Cube.js configuration — multi-tenant CPG + cold chain
// Domain-based model routing + JWT auth + Row-Level Security queryRewrite

const jwt = require("jsonwebtoken");
const { FileRepository } = require("@cubejs-backend/server-core");

module.exports = {
  // ── Database ───────────────────────────────────────────────────────────────
  // PostgreSQL — multi-schema (cpg_nestle / cpg_unilever / cpg_itc / cold_chain_*)
  dbType: "postgres",

  // ── Dynamic model directory based on tenant domain ─────────────────────────
  // cpg → model/cpg/*, cold_chain → model/cold_chain/*
  repositoryFactory: ({ securityContext }) => {
    const domain = securityContext?.domain || "cpg";
    return new FileRepository(`model/${domain}`);
  },

  // ── Per-tenant compiled schema cache ──────────────────────────────────────
  contextToAppId: ({ securityContext }) => {
    const clientId = (securityContext?.clientId || "default").toUpperCase();
    const domain   = (securityContext?.domain   || "cpg");
    return `APP_${domain}_${clientId}`;
  },

  contextToOrchestratorId: ({ securityContext }) => {
    const clientId = (securityContext?.clientId || "default").toUpperCase();
    return `ORCH_${clientId}`;
  },

  // ── JWT authentication ─────────────────────────────────────────────────────
  // Token generated by FastAPI (backend/app/core/security.py → create_cubejs_token)
  checkAuth: async (req, auth) => {
    // /meta: schema introspection only — allow without token (no data access)
    const path = req.url || req.path || "";
    if (path.includes("/meta") && !auth) {
      req.securityContext = { clientId: "nestle", role: "analyst", domain: "cpg" };
      return;
    }

    if (!auth) throw new Error("No authorization token provided");

    const secret = process.env.CUBEJS_API_SECRET;
    if (!secret) throw new Error("CUBEJS_API_SECRET not configured");

    try {
      const payload = jwt.verify(auth, secret, { algorithms: ["HS256"] });
      req.securityContext = payload;
    } catch (e) {
      throw new Error(`JWT verification failed: ${e.message}`);
    }
  },

  // ── Row-Level Security ─────────────────────────────────────────────────────
  // Hierarchy-restricted roles (SO/ASM/ZSM) get their territory code injected
  // as a Cube.js filter. Admin/NSM/analyst see all data.
  queryRewrite: (query, { securityContext }) => {
    if (!securityContext) return query;

    const { role, hierarchyCode } = securityContext;
    const restrictedRoles = ["SO", "ASM", "ZSM"];

    if (restrictedRoles.includes(role) && hierarchyCode) {
      const roleToMember = {
        SO:  "DimSalesHierarchy.soCode",
        ASM: "DimSalesHierarchy.asmCode",
        ZSM: "DimSalesHierarchy.zsmCode",
      };
      const filterMember = roleToMember[role];
      if (filterMember) {
        query.filters = query.filters || [];
        query.filters.push({
          member:   filterMember,
          operator: "equals",
          values:   [hierarchyCode],
        });
      }
    }

    return query;
  },

  // ── Pre-aggregation namespace ──────────────────────────────────────────────
  preAggregationsSchema: "cube_pre_agg",

  // ── CORS — FastAPI backend is the only caller ──────────────────────────────
  http: {
    cors: { origin: "*" },
  },

  // ── Dev mode ───────────────────────────────────────────────────────────────
  devServer: process.env.NODE_ENV !== "production",

  logger: (msg, params) => {
    if (process.env.NODE_ENV !== "production") {
      console.log(`[Cube.js] ${msg}`, params || "");
    }
  },
};
